
    #Base image fedora:latest
    FROM fedora:latest
    #Run an upgrade of the system using the dnf command
    Install the dnf-plugin-system-upgrade package
    #Install the tuxpaint, vim,and httpd applications.
    Install tuxpaint
    Install vim
    RUN yum install -y httpd
    #Add the myinfo.html file to the container at the /var/www/html/ location.
    cd myinfo.html /var/www/html/
    #Expose port 80/tcp.
    EXPOSE 80
    #Enable the httpd service using the following directive.
        ENTRYPOINT "/usr/sbin/httpd", "-D", "FOREGROUND"
